<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Tilawa.Core.Domain.Model" />
    <PackageReference Include="GirCore.Adw-1" Version="0.8.1" />
    <PackageReference Include="Tilawa.Core" Version="0.1.0" />
  </ItemGroup>
</Project>
